---
- name: Test MongoDB Installation
  hosts: mongodb
  become: yes
  vars_files:
    - vars/mongodb_vars.yml
  tasks:
    - name: Check MongoDB service status
      command: systemctl status {{ mongodb_service_name }}
      register: service_status
      changed_when: false
      
    - name: Display service status
      debug:
        var: service_status.stdout_lines
        
    - name: Check MongoDB version
      command: mongod --version
      register: mongodb_version
      changed_when: false
      
    - name: Display MongoDB version
      debug:
        var: mongodb_version.stdout_lines
        
    - name: Check MongoDB connection
      command: mongosh --authenticationDatabase admin -u {{ mongodb_admin_user }} -p {{ mongodb_admin_pass }} --eval "db.adminCommand('ping')"
      register: mongodb_ping
      changed_when: false
      
    - name: Display MongoDB connection result
      debug:
        var: mongodb_ping.stdout_lines
        
    - name: Create test database and collection
      block:
        - name: Create test document
          copy:
            content: |
              use test_db;
              db.test_collection.insertOne({ "name": "Test Document", "created_at": new Date() });
              db.test_collection.find();
              exit;
            dest: /tmp/mongodb_test.js
            mode: '0644'
            
        - name: Run test script
          command: mongosh --authenticationDatabase admin -u {{ mongodb_admin_user }} -p {{ mongodb_admin_pass }} --file /tmp/mongodb_test.js
          register: test_result
          changed_when: false
          
        - name: Display test result
          debug:
            var: test_result.stdout_lines
            
        - name: Clean up test script
          file:
            path: /tmp/mongodb_test.js
            state: absent
